trigger:
- main

resources:
  repositories:
  - repository: templates
    type: git
    name: DevopsTools/prodest-build-deploy-templates

variables:
  BuildConfiguration: Release
  BuildPlatform: any cpu
  system.debug: true
  NODE_TLS_REJECT_UNAUTHORIZED: '0'

jobs:
- template: buildDeployDocs.yml@templates
  parameters:
    environment: IISProducao
    sistema: docs.admin.acessocidadao
    orgao: Prodest
    diretorioraiz: D:\Sites\$(Orgao)\$(Sistema)
    hostname: $(Sistema).es.gov.br